openel-arduino: index.md: add that python and python-serial are required as dependency
I encountered an issue where there were two missing dependencies
undocumented while following this document on a relatively fresh
Ubuntu 20.04 installation.

Here are the two compile errors:

1. `python` command is not found:

	Multiple libraries were found for "WiFiClient.h"
	 Used: /home/ytsuchiya/.arduino15/packages/m5stack/hardware/esp32/2.0.2/libraries/WiFi
	 Not used: /home/ytsuchiya/bin/arduino-1.8.19/libraries/WiFi
	Multiple libraries were found for "SD.h"
	 Used: /home/ytsuchiya/.arduino15/packages/m5stack/hardware/esp32/2.0.2/libraries/SD
	 Not used: /home/ytsuchiya/bin/arduino-1.8.19/libraries/SD
	exec: "python": executable file not found in $PATH
	Error compiling for board M5Stack-Core-ESP32.

2. `serial` module is not found:

	Traceback (most recent call last):
	  File "/home/ytsuchiya/.arduino15/packages/m5stack/tools/esptool_py/3.1.0/esptool.py", line 38, in <module>
	    import serial
	ModuleNotFoundError: No module named 'serial'
	Multiple libraries were found for "SD.h"
	 Used: /home/ytsuchiya/.arduino15/packages/m5stack/hardware/esp32/2.0.2/libraries/SD
	 Not used: /home/ytsuchiya/bin/arduino-1.8.19/libraries/SD
	Multiple libraries were found for "WiFiClient.h"
	 Used: /home/ytsuchiya/.arduino15/packages/m5stack/hardware/esp32/2.0.2/libraries/WiFi
	 Not used: /home/ytsuchiya/bin/arduino-1.8.19/libraries/WiFi
	exit status 1
	Error compiling for board M5Stack-Core-ESP32.

These errors can be fixed by installing `python-is-python3` and
`python3-serial` packages, respectively.

This patch adds the two missing dependencies into the document, as well
as an example for Ubuntu 20.04 system.